//
//  CoinsListRouter.swift
//  MarketCoins
//
//  Created by Robson Moreira on 06/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CoinsListRoutingLogic {
    func routeToCoin(segue: UIStoryboardSegue?)
}

protocol CoinsListDataPassing {
    var dataStore: CoinsListDataStore? { get }
}

class CoinsListRouter: NSObject, CoinsListRoutingLogic, CoinsListDataPassing {
    
    weak var viewController: CoinsListViewController?
    var dataStore: CoinsListDataStore?
    
    // MARK: Routing
    
    func routeToCoin(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! CoinViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCoin(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! CoinViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCoin(source: dataStore!, destination: &destinationDS)
            navigateToCoin(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToCoin(source: CoinsListViewController, destination: CoinViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToCoin(source: CoinsListDataStore, destination: inout CoinDataStore) {
        let selectedRow = viewController?.listCoinsTableView.indexPathForSelectedRow?.row
        destination.coin = source.coins?[selectedRow!]
    }
}
