//
//  CoinViewController.swift
//  MarketCoins
//
//  Created by Robson Moreira on 07/11/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Charts

protocol CoinDisplayLogic: AnyObject {
    func displayCoin(viewModel: Coin.FetchCurrentData.ViewModel)
    func displayMarketChart(viewModel: Coin.FetchMarketChart.ViewModel)
    func displayError(error: String)
}

class CoinViewController: ViewController {
    
    @IBOutlet weak var coinValuesView: UIView! {
        didSet {
            coinValuesView.isHidden = true
        }
    }
    @IBOutlet weak var coinCurrentPriceBaseCurrencyLabel: UILabel!
    @IBOutlet weak var changePercentageLabel: UILabel!
    @IBOutlet weak var marketDataCoinCurrentPriceLabel: UILabel!
    @IBOutlet weak var marketDataCoinIconImageView: UIImageView!
    @IBOutlet weak var marketDataCoinSymbolLabel: UILabel!
    @IBOutlet weak var marketDataComparationActionView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didComparationCoin))
            marketDataComparationActionView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketDataComparationCurrencyPriceLabel: UILabel!
    @IBOutlet weak var marketDataComparationSymbolLabel: UILabel!
    
    @IBOutlet weak var coinGraphicView: UIView! {
        didSet {
            coinGraphicView.isHidden = true
        }
    }
    @IBOutlet weak var marketChartView: LineChartView!
    @IBOutlet weak var marketChartOneHourView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketChartOneHour))
            marketChartOneHourView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketChartOneDayView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketChartOneDay))
            marketChartOneDayView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketChartOneWeekView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketChartOneWeek))
            marketChartOneWeekView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketChartOneMonthView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketChartOneMonth))
            marketChartOneMonthView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketChartThreeMonthsView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketThreeMonths))
            marketChartThreeMonthsView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketChartOneYearView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketChartOneYear))
            marketChartOneYearView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var marketChartMaximumView: UIView! {
        didSet {
            let gesture = UITapGestureRecognizer(target: self, action: #selector (didChangeMarketChartMaximum))
            marketChartMaximumView.addGestureRecognizer(gesture)
        }
    }
    @IBOutlet weak var priceChangePercentageOneDayLabel: UILabel!
    @IBOutlet weak var priceChangePercentageOneWeekLabel: UILabel!
    @IBOutlet weak var priceChangePercentageTwoWeeksLabel: UILabel!
    @IBOutlet weak var priceChangePercentageOneMonthLabel: UILabel!
    @IBOutlet weak var priceChangePercentageTwoMonthsLabel: UILabel!
    @IBOutlet weak var priceChangePercentageOneYearLabel: UILabel!
    
    @IBOutlet weak var coinResumeView: UIView! {
        didSet {
            coinResumeView.isHidden = true
        }
    }
    @IBOutlet weak var marketClassificationRankLabel: UILabel!
    @IBOutlet weak var marketCapitalizationLabel: UILabel!
    @IBOutlet weak var fullyDilutedValuationLabel: UILabel!
    @IBOutlet weak var volumeBusinessLabel: UILabel!
    @IBOutlet weak var twentyFourHourHighLabel: UILabel!
    @IBOutlet weak var twentyFourHourLowLabel: UILabel!
    @IBOutlet weak var supplyAvailableLabel: UILabel!
    @IBOutlet weak var totalSupplyLabel: UILabel!
    @IBOutlet weak var maximumSupplyLabel: UILabel!
    @IBOutlet weak var maximumValueLabel: UILabel!
    @IBOutlet weak var maximumPercentageLabel: UILabel!
    @IBOutlet weak var maximumDateLabel: UILabel!
    @IBOutlet weak var minimumValueLabel: UILabel!
    @IBOutlet weak var minimumPercentageLabel: UILabel!
    @IBOutlet weak var minimumDateLabel: UILabel!
    
    private lazy var coinsFilterView: FiltersView = {
        let filterView = FiltersView()
        filterView.isHidden = true
        filterView.delegate = self
        filterView.filterOptions = filtersUtils.coinsFilter
        return filterView
    }()
    
    private var viewModel: Coin.FetchCurrentData.ViewModel?
    private let filtersUtils = FiltersUtils.shared
    private var timeSelection = DateTimeEnum.hour
    private var typeDateValueFormatter = DateValueFormatterEnum.hour
    
    var interactor: CoinBusinessLogic?
    var router: (NSObjectProtocol & CoinRoutingLogic & CoinDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(coinsFilterView)
        
        setupCoinFilter()
        setupGraphic()
        
        doFetchCurrentData()
        doFetchMarketChartHourly()
    }
    
    override func setup() {
        let viewController = self
        let interactor = CoinInteractor()
        let presenter = CoinPresenter()
        let router = CoinRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    func setupCoinFilter() {
        let filter = filtersUtils.getSelectedCoinsFilter()
        switch filter {
        case .brl:
            coinsFilterView.filterPickerView.selectRow(0, inComponent: 0, animated: true)
        case .usd:
            coinsFilterView.filterPickerView.selectRow(1, inComponent: 0, animated: true)
        case .eur:
            coinsFilterView.filterPickerView.selectRow(2, inComponent: 0, animated: true)
        }
    }
    
    func setupGraphic() {
        marketChartView.delegate = self
        marketChartView.rightAxis.enabled = false
        
        marketChartView.leftAxis.labelFont = .systemFont(ofSize: 9)
        marketChartView.leftAxis.setLabelCount(6, force: true)
        marketChartView.leftAxis.labelTextColor = .white
        marketChartView.leftAxis.axisLineColor = .white
        marketChartView.leftAxis.labelPosition = .outsideChart
        
        marketChartView.xAxis.labelPosition = .bottom
        marketChartView.xAxis.labelFont = .systemFont(ofSize: 9)
        marketChartView.xAxis.setLabelCount(6, force: true)
        marketChartView.xAxis.labelTextColor = .white
        marketChartView.xAxis.axisLineColor = .systemBlue
    }
    
    func doFetchCurrentData() {
        MarketCoinsLoading.shared.start(from: view)
        
        let baseCoin = filtersUtils.getSelectedCoinsFilter()
        let request = Coin.FetchCurrentData.Request(baseCoin: baseCoin)
        interactor?.doFetchCurrentData(request: request)
    }
    
    func doFetchMarketChartHourly() {
        marketChartView.isHidden = true
        MarketCoinsLoading.shared.start(from: coinGraphicView, isBackground: false, isLarge: false)
        
        let baseCoin = filtersUtils.getSelectedCoinsFilter()
        let from = Date().addingTimeInterval(-60 * 60)
        let to = Date()
        
        let request = Coin.FetchMarketChart.Request(baseCoin: baseCoin, from: from, to: to)
        interactor?.doFetchMarketChart(request: request)
    }
    
    func doFetchMarketChart() {
        marketChartView.isHidden = true
        MarketCoinsLoading.shared.start(from: coinGraphicView, isBackground: false, isLarge: false)
        
        let baseCoin = filtersUtils.getSelectedCoinsFilter()
        let request = Coin.FetchOhlc.Request(baseCoin: baseCoin, day: timeSelection.rawValue)
        interactor?.doFetchOhlc(request: request)
    }
    
    @objc func didComparationCoin() {
        coinsFilterView.cellRow = 0
        UIView.transition(with: coinsFilterView, duration: 0.5, options: .transitionCrossDissolve) {
            self.coinsFilterView.isHidden = false
        }
    }
    
    @objc func didChangeMarketChartOneHour() {
        timeSelection = .hour
        typeDateValueFormatter = DateValueFormatterEnum.hour
        doFetchMarketChartHourly()
        
        UIView.transition(with: marketChartOneHourView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .black
            self.marketChartOneDayView.backgroundColor = .clear
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .clear
        }
    }
    
    @objc func didChangeMarketChartOneDay() {
        timeSelection = .day
        typeDateValueFormatter = DateValueFormatterEnum.day
        doFetchMarketChart()
        
        UIView.transition(with: marketChartOneDayView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .clear
            self.marketChartOneDayView.backgroundColor = .black
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .clear
        }
    }
    
    @objc func didChangeMarketChartOneWeek() {
        timeSelection = .weak
        typeDateValueFormatter = DateValueFormatterEnum.month
        doFetchMarketChart()
        
        UIView.transition(with: marketChartOneWeekView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .clear
            self.marketChartOneDayView.backgroundColor = . clear
            self.marketChartOneWeekView.backgroundColor = .black
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .clear
        }
    }
    
    @objc func didChangeMarketChartOneMonth() {
        timeSelection = .month
        typeDateValueFormatter = DateValueFormatterEnum.month
        doFetchMarketChart()
        
        UIView.transition(with: marketChartOneMonthView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .clear
            self.marketChartOneDayView.backgroundColor = . clear
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .black
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .clear
        }
    }
    
    @objc func didChangeMarketThreeMonths() {
        timeSelection = .threeMonths
        typeDateValueFormatter = DateValueFormatterEnum.month
        doFetchMarketChart()
        
        UIView.transition(with: marketChartThreeMonthsView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .clear
            self.marketChartOneDayView.backgroundColor = . clear
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .black
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .clear
        }
    }
    
    @objc func didChangeMarketChartOneYear() {
        timeSelection = .year
        typeDateValueFormatter = DateValueFormatterEnum.month
        doFetchMarketChart()
        
        UIView.transition(with: marketChartOneYearView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .clear
            self.marketChartOneDayView.backgroundColor = . clear
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .black
            self.marketChartMaximumView.backgroundColor = .clear
        }
    }
    
    @objc func didChangeMarketChartMaximum() {
        timeSelection = .max
        typeDateValueFormatter = DateValueFormatterEnum.year
        doFetchMarketChart()
        
        UIView.transition(with: marketChartMaximumView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .clear
            self.marketChartOneDayView.backgroundColor = . clear
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .black
        }
    }
}

extension CoinViewController: CoinDisplayLogic {
    
    func displayCoin(viewModel: Coin.FetchCurrentData.ViewModel) {
        DispatchQueue.main.async {
            self.title = viewModel.coinName
            self.viewModel = viewModel
            
            self.coinValuesView.isHidden = false
            self.coinCurrentPriceBaseCurrencyLabel.text = viewModel.currentPrice
            self.changePercentageLabel.attributedText = viewModel.priceChangePercentage
            self.marketDataCoinCurrentPriceLabel.text = viewModel.coinPrice
            self.marketDataCoinIconImageView.loadImage(from: viewModel.coinImage)
            self.marketDataCoinSymbolLabel.text = viewModel.coinSymbol
            self.marketDataComparationCurrencyPriceLabel.text = viewModel.currentPriceComparationToCoin
            self.marketDataComparationSymbolLabel.text = viewModel.comparationToCoinSymbol
            
            self.coinGraphicView.isHidden = false
            self.priceChangePercentageOneDayLabel.attributedText  = viewModel.priceChangePercentageOneDay
            self.priceChangePercentageOneWeekLabel.attributedText  = viewModel.priceChangePercentageOneWeek
            self.priceChangePercentageTwoWeeksLabel.attributedText  = viewModel.priceChangePercentageTwoWeeks
            self.priceChangePercentageOneMonthLabel.attributedText  = viewModel.priceChangePercentageOneMonth
            self.priceChangePercentageTwoMonthsLabel.attributedText  = viewModel.priceChangePercentageTwoMonths
            self.priceChangePercentageOneYearLabel.attributedText  = viewModel.priceChangePercentageOneYear
            
            self.coinResumeView.isHidden = false
            self.marketClassificationRankLabel.text = viewModel.marketCapRank
            self.marketCapitalizationLabel.text = viewModel.marketCap
            self.fullyDilutedValuationLabel.text = viewModel.fullyDilutedValuation
            self.volumeBusinessLabel.text = viewModel.totalVolume
            self.twentyFourHourHighLabel.text = viewModel.high24h
            self.twentyFourHourLowLabel.text = viewModel.low24h
            self.supplyAvailableLabel.text = viewModel.supplyAvailable
            self.totalSupplyLabel.text = viewModel.totalSupply
            self.maximumSupplyLabel.text = viewModel.maxSupply
            self.maximumValueLabel.text = viewModel.maximumValue
            self.maximumPercentageLabel.text = viewModel.maximumValuePercentage
            self.maximumDateLabel.text = viewModel.maximumValueDate
            self.minimumValueLabel.text = viewModel.minimumValue
            self.minimumPercentageLabel.text = viewModel.minimumValuePercentage
            self.minimumDateLabel.text = viewModel.minimumValueDate
            
            MarketCoinsLoading.shared.stop(from: self.view)
        }
    }
    
    func displayMarketChart(viewModel: Coin.FetchMarketChart.ViewModel) {
        DispatchQueue.main.async {
            self.setData(from: viewModel.dataEntries,
                         minPrice: viewModel.minimumPrice,
                         maxPrice: viewModel.maximumPrice)
            
            self.marketChartView.isHidden = false
            MarketCoinsLoading.shared.stop(from: self.coinGraphicView)
        }
    }
    
    func displayError(error: String) {
        DispatchQueue.main.async {
            MarketCoinsLoading.shared.stop(from: self.view)
            MarketCoinsLoading.shared.stop(from: self.coinGraphicView )
            
            self.showError(for: error) { action in
                self.doFetchCurrentData()
                self.doFetchMarketChartHourly()
            }
        }
    }
    
    private func setData(from entry: [ChartDataEntry], minPrice: Double, maxPrice: Double) {
        let baseCoin = filtersUtils.getSelectedCoinsFilter()
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .currency
        numberFormatter.locale = Locale(identifier: baseCoin.locale)
        
        marketChartView.leftAxis.valueFormatter = DefaultAxisValueFormatter(formatter: numberFormatter)
        marketChartView.leftAxis.axisMinimum = minPrice
        marketChartView.leftAxis.axisMaximum = maxPrice
        
        marketChartView.xAxis.valueFormatter = DateValueFormatter(chart: marketChartView, type: typeDateValueFormatter)
        
        let dataSet = LineChartDataSet(entries: entry, label: "")
        setupDataSet(dataSet)
    }
    
    private func setupDataSet(_ dataSet: LineChartDataSet) {
        dataSet.mode = .cubicBezier
        dataSet.drawCirclesEnabled = false
        dataSet.lineWidth = 2
        dataSet.setColor(.systemBlue, alpha: 0.8)
        
        dataSet.gradientPositions = [100, 0, 100]
        let gradientColors = [
            ChartColorTemplates.colorFromString("#0080bf").cgColor,
            ChartColorTemplates.colorFromString("#00acdf").cgColor
        ]
        let gradient = CGGradient(colorsSpace: nil, colors: gradientColors as CFArray, locations: nil)!
        dataSet.fill = LinearGradientFill(gradient: gradient, angle: 90)
        
        dataSet.fillAlpha = 0.8
        dataSet.drawFilledEnabled = true
        
        dataSet.drawHorizontalHighlightIndicatorEnabled = false
        dataSet.highlightColor = .systemRed
        
        let data = LineChartData(dataSet: dataSet)
        data.setDrawValues(false)
        marketChartView.data = data
    }
}

extension CoinViewController: ToolbarFiltersViewDelegate {
    
    func filtersView(_ filtersView: FiltersView, didSelect filter: Filter, forCellRow row: Int) {
        filtersUtils.setSelectedFilter(to: filter, of: row)
        
        doFetchCurrentData()
        doFetchMarketChartHourly()
        
        UIView.transition(with: marketChartOneHourView, duration: 0.5, options: .transitionCrossDissolve) {
            self.marketChartOneHourView.backgroundColor = .black
            self.marketChartOneDayView.backgroundColor = .clear
            self.marketChartOneWeekView.backgroundColor = .clear
            self.marketChartOneMonthView.backgroundColor = .clear
            self.marketChartThreeMonthsView.backgroundColor = .clear
            self.marketChartOneYearView.backgroundColor = .clear
            self.marketChartMaximumView.backgroundColor = .clear
        }
        
        cancelFilter(for: filtersView)
    }
    
    func cancelFilter(for filtersView: FiltersView) {
        UIView.transition(with: filtersView, duration: 0.5, options: .transitionCrossDissolve) {
            filtersView.isHidden = true
        }
    }
}

extension CoinViewController: ChartViewDelegate {
    
    func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        let baseCoin = filtersUtils.getSelectedCoinsFilter()
        let value = entry.y.toCurrency(from: baseCoin)
        
        coinCurrentPriceBaseCurrencyLabel.text = value
        changePercentageLabel.text = ""
    }
    
    func chartViewDidEndPanning(_ chartView: ChartViewBase) {
        coinCurrentPriceBaseCurrencyLabel.text = viewModel?.currentPrice
        changePercentageLabel.attributedText = viewModel?.priceChangePercentage
    }
}
